version: "3.9"
volumes:
  prometheusdata:
  grafanadata:
  lokidata:

services:
  prometheus:
    image: prom/prometheus:v2.36.1
    user: "0:0"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheusdata:/prometheus/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=/prometheus/'
      - '--web.route-prefix=/prometheus/'
      - '--web.enable-admin-api'
    deploy:
       labels:
         - traefik.frontend.rule=Host:monitoring.smartfizz.fr;PathPrefix:/prometheus/
         - traefik.port=9090
    ports:
     - 127.0.0.1:9090:9090
  grafana:
    image: grafana/grafana:9.0.0
    volumes:
      - ./grafana/conf/:/run/conf/
      - grafanadata:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/conf/admin_password
      - GF_SERVER_DOMAIN__FILE=/run/conf/domain
      - GF_SERVER_SERVE_FROM_SUB_PATH__FILE=/run/conf/subpath
      - GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION=false
      - GF_SECURITY_DISABLE_BRUTE_FORCE_LOGIN_PROTECTION__FILE=/run/conf/bruteforce
      - GF_SMTP_ADMIN_PASSWORD__FILE=/run/conf/admin_password
      - GF_SMTP_ENABLED__FILE=/run/conf/smtp_enabled
      - GF_SMTP_FROM_NAME__FILE=/run/conf/smtp_from_name
      - GF_SMTP_HOST__FILE=/run/conf/smtp_host
      - GF_SMTP_PASSWORD__FILE=/run/conf/smtp_password
      - GF_AUTH_BASIC_ENABLED=false
      - GF_QUERY_HISTORY_ENABLED=false
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - 127.0.0.1:3000:3000
  loki:
    image: grafana/loki:2.5.0
    volumes:
      - ./loki:/etc/loki
    command:
      - '-config.file=/etc/loki/local-config.yaml'
    ports:
      - 127.0.0.1:3100:3100
  nodeexporter:
    image: prom/node-exporter:v1.5.0
    ports:
      - 127.0.0.1:9100:9100
